#!/usr/bin/env python3
"""build-versemap.py — regenerates pilgrim-private/versemap.js from the Open Scriptures verse map.

Source: openscriptures/morphhb, wlc/VerseMap.xml ("versification differences between the Westminster
Leningrad Codex (wlc) and the King James Version (kjv)"). Our Old Testament word data (data/macula/01-39)
comes from the same project, so its verse numbers are the WLC (Hebrew) numbers.

Usage (from repo root):
  curl -sO https://raw.githubusercontent.com/openscriptures/morphhb/master/wlc/VerseMap.xml
  python3 data/build-versemap.py VerseMap.xml pilgrim-private/versemap.js

Output encoding (see versemap.js): runs of consecutive English -> Hebrew verse pairs, the list of
Hebrew verses that have no English verse number of their own ("orphans": Psalm titles and a few split
verses), and the list of Hebrew verses that are only half of an English verse ("partial").
"""
import re, sys, json, collections

BOOKS = ['Gen','Exod','Lev','Num','Deut','Josh','Judg','Ruth','1Sam','2Sam','1Kgs','2Kgs','1Chr','2Chr','Ezra','Neh','Esth','Job','Ps','Prov','Eccl','Song','Isa','Jer','Lam','Ezek','Dan','Hos','Joel','Amos','Obad','Jonah','Mic','Nah','Hab','Zeph','Hag','Zech','Mal']
BN = {b: i + 1 for i, b in enumerate(BOOKS)}

def key(s):
    p = s.split('!')[0].split('.')
    return (BN[p[0]], int(p[1]), int(p[2]))

def main(xml_path, out_path, macula_dir='data/macula'):
    s = open(xml_path, encoding='utf-8').read()
    rows = [dict(re.findall(r'(\w+)="([^"]*)"', e)) for e in re.findall(r'<verse\s+([^>]*?)/?>', s)]
    pairs = [(key(r['kjv']), key(r['wlc']), r['type']) for r in rows]
    hebrew = set()
    for n in range(1, 40):
        d = json.load(open('%s/%02d.json' % (macula_dir, n), encoding='utf-8'))
        for k in d:
            c, v = map(int, k.split(':'))
            hebrew.add((n, c, v))
    missing = [p for p in pairs if p[1] not in hebrew]
    if missing:
        sys.exit('map points at Hebrew verses that do not exist in data/macula: %r' % missing[:5])
    targets = {p[1] for p in pairs}
    english_keys = {p[0] for p in pairs}
    # Hebrew verses that no English verse points at AND whose own number is used by a different English verse
    orphans = sorted(h for h in hebrew if h not in targets and h in english_keys)
    partial = sorted({p[1] for p in pairs if p[2] == 'partial'})
    # runs: consecutive pairs where both sides advance by one verse in the same chapters
    by_book = collections.OrderedDict()
    for e, h, _ in pairs:
        by_book.setdefault(e[0], []).append((e[1], e[2], h[1], h[2]))
    out_books = {}
    for b, lst in by_book.items():
        runs = []
        for ec, ev, hc, hv in lst:
            if runs:
                r = runs[-1]
                if r[0] == ec and r[2] == hc and r[1] + r[4] == ev and r[3] + r[4] == hv:
                    r[4] += 1
                    continue
            runs.append([ec, ev, hc, hv, 1])
        out_books[b] = runs
    js = '''// ════════════════════════════════════════════════════════
// versemap.js — Pilgrim Private (v4.44.0). GENERATED by data/build-versemap.py — do not edit by hand.
// English (KJV) verse -> Hebrew (WLC) verse(s) for the Old Testament, so Interlinear can show the right
// Hebrew words for an English verse number (Psalm titles, Joel 2-3, Malachi 3-4, Genesis 31-32, ...).
// Source: openscriptures/morphhb wlc/VerseMap.xml (see data/README.md). %d pairs, %d Hebrew-only verses.
// Pure functions, no imports, nothing stored.
// ════════════════════════════════════════════════════════

// Runs: [englishChapter, englishVerse, hebrewChapter, hebrewVerse, length] per book number 1-39. Run item i maps
// English (ec, ev+i) -> Hebrew (hc, hv+i). An English verse can appear in more than one run (it covers several Hebrew verses).
var VM_RUNS = %s;
// Hebrew verses with no English verse number of their own: [book, chapter, verse]. Each belongs with the English verse that
// has the same number (Psalm titles belong with verse 1).
var VM_ORPHANS = %s;
// Hebrew verses that are only half of an English verse (the other half sits in the neighbouring verse): [book, chapter, verse].
var VM_PARTIAL = %s;

var _vmIdx = null, _vmOrph = null, _vmPart = null;
function _vmBuild(){
  if(_vmIdx)return;
  _vmIdx = {};
  Object.keys(VM_RUNS).forEach(function(b){
    VM_RUNS[b].forEach(function(r){
      for(var i = 0; i < r[4]; i++){
        var k = b + ':' + r[0] + ':' + (r[1] + i);
        (_vmIdx[k] = _vmIdx[k] || []).push([r[2], r[3] + i]);
      }
    });
  });
  _vmOrph = {}; VM_ORPHANS.forEach(function(o){_vmOrph[o.join(':')] = 1;});
  _vmPart = {}; VM_PARTIAL.forEach(function(o){_vmPart[o.join(':')] = 1;});
}

/**
 * The Hebrew verse(s) that hold the words of an English verse.
 * @param {number} book - Book number 1-39 (Old Testament).
 * @param {number} c - English chapter.
 * @param {number} v - English verse.
 * @returns {{verses:{c:number,v:number,title:boolean,partial:boolean}[], differs:boolean}}
 *   verses in Hebrew order; differs is false when the English and Hebrew numbering are identical (one whole verse, same number).
 */
function hebrewVerses(book, c, v){
  _vmBuild();
  var seen = {}, list = [];
  function add(hc, hv){var k = hc + ':' + hv; if(!seen[k]){seen[k] = 1; list.push([hc, hv]);}}
  var mapped = _vmIdx[book + ':' + c + ':' + v];
  if(mapped)mapped.forEach(function(m){add(m[0], m[1]);});
  else add(c, v);
  if(_vmOrph[book + ':' + c + ':' + v])add(c, v);
  list.sort(function(a, b){return a[0] - b[0] || a[1] - b[1];});
  var verses = list.map(function(m){
    return {c: m[0], v: m[1], title: book === 19 && _vmOrph[book + ':' + m[0] + ':' + m[1]] === 1 && m[1] === 1, partial: !!_vmPart[book + ':' + m[0] + ':' + m[1]]};
  });
  var differs = verses.length !== 1 || verses[0].c !== c || verses[0].v !== v || verses[0].partial;
  return {verses: verses, differs: differs};
}

export { hebrewVerses, VM_RUNS, VM_ORPHANS, VM_PARTIAL };
''' % (len(pairs), len(orphans),
       json.dumps({str(b): r for b, r in out_books.items()}, separators=(',', ':')),
       json.dumps([list(o) for o in orphans], separators=(',', ':')),
       json.dumps([list(o) for o in partial], separators=(',', ':')))
    open(out_path, 'w', encoding='utf-8').write(js)
    print('pairs', len(pairs), 'runs', sum(len(v) for v in out_books.values()), 'orphans', len(orphans), 'partial', len(partial), 'bytes', len(js.encode('utf-8')))

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
